---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Login to ACR with Podman locally
      containers.podman.podman_login:
        registry: "{{ acr_login_server }}"
        username: "{{ acr_admin_username }}"
        password: "{{ acr_admin_password }}"

    - name: Pull required images from DockerHub
      containers.podman.podman_image:
        name: "{{ item.name }}"
        state: present
        arch: amd64
      loop:
        - name: "{{ image_nginx }}"
        - name: "{{ image_front }}"
        - name: "{{ image_back }}"
      become: false
    
    - name: Tag image for ACR
      containers.podman.podman_tag:
        image: "{{ item.name }}"
        target_names:
          - "{{ acr_login_server }}/{{ item.opt }}/{{ item.id }}:{{ item.tag }}"
      loop:
        - {name: "{{ image_nginx }}",opt: caso1, id: nginx, tag: "{{ tag }}"}
        - {name: "{{ image_front }}",opt: caso2, id: front,tag: "{{ tag }}"}
        - {name: "{{ image_front }}",opt: caso2, id: backend, tag: "{{ tag }}"}
      become: false


    - name: Push image to ACR
      containers.podman.podman_image:
        name: "{{ acr_login_server }}/{{ item.opt }}/{{ item.id }}:{{ item.tag }}"
        push: true
        username: "{{ acr_admin_username }}"
        password: "{{ acr_admin_password }}"
      loop:
        - {name: "{{ image_nginx }}", opt: caso1, id: nginx, tag: "{{ tag }}"}
        - {name: "{{ image_front }}", opt: caso2, id: front, tag: "{{ tag }}"}
        - {name: "{{ image_back }}", opt: caso2, id: backend, tag: "{{ tag }}"}
      become: false


- hosts: [cp2Caso1]
  become: true
  tasks:
    - name: Login to ACR desde root para systemd
      containers.podman.podman_login:
        registry: "{{ acr_login_server }}"
        username: "{{ acr_admin_username }}"
        password: "{{ acr_admin_password }}"
      become: true

    - name: Install dependencies for Podman repo
      ansible.builtin.apt:
        name:
          - software-properties-common
          - uidmap
        state: present

    - name: Add repo GPG key
      ansible.builtin.apt_key:
        url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key"
        state: present

    - name: Add Podman repo
      ansible.builtin.apt_repository:
        repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /"
        state: present
        filename: "devel:kubic:libcontainers:stable"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Podman
      ansible.builtin.apt:
        name: podman
        state: present

    - name: Pull nginx image from ACR (guaranteed amd64)
      containers.podman.podman_image:
        name: "{{ acr_login_server }}/caso1/nginx:casopractico2"
        state: present
        username: "{{ acr_admin_username }}"
        password: "{{ acr_admin_password }}"
      become: true

    - name: Ensure html directory exists
      ansible.builtin.file:
        path: "/home/{{ user_vm }}/html"
        state: directory
        owner: "{{ user_vm }}"
        mode: "0755"

    - name: Create custom index.html
      ansible.builtin.copy:
        dest: "/home/{{ user_vm }}/html/index.html"
        content: |
          <html>
          <head><title>Nginx Caso 1</title></head>
          <body><h1>Hola desde el Caso Practico 2 con Podman</h1></body>
          </html>
        owner: "{{ user_vm }}"
        mode: "0644"

    - name: Remove nginx container if exists
      containers.podman.podman_container:
        name: nginx-web
        state: absent
      ignore_errors: true
      become: false

    - name: Crear y arrancar contenedor nginx-web
      containers.podman.podman_container:
        name: nginx-web
        image: "{{ acr_login_server }}/caso1/nginx:casopractico2"
        state: started
        recreate: yes
        restart_policy: always
        detach: yes
        ports:
          - "8080:80"
        volumes:
          - "/home/{{ user_vm }}/html:/usr/share/nginx/html:ro"
      become: false
      environment:
        XDG_RUNTIME_DIR: "/run/user/1000"


      
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aks_resource_group: "{{ lookup('pipe', 'terraform -chdir=../terraform output -raw aks_resource_group') }}"
    aks_cluster_name: "{{ lookup('pipe', 'terraform -chdir=../terraform output -raw aks_cluster_name') }}"
    aks_kubeconfig: "{{ lookup('pipe', 'terraform -chdir=../terraform output -raw aks_kubeconfig') }}"
  tasks:
    - name: Guardar kubeconfig generado por Terraform
      copy:
        content: "{{ aks_kubeconfig }}"
        dest: "~/.kube/config"
        mode: 0600

    - name: Aplicar todos los manifiestos en AKS
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
        kubeconfig: "~/.kube/config"
        namespace: default
      with_fileglob:
        - "../k8s/persistent-volumes/*.yml"
        - "../k8s/deployments/*.yml"
        
